-- singularity.nvim — an ember-toned Neovim colorscheme.
--
-- A pure-Lua descendant of oxocarbon.nvim (IBM Carbon inspired), restyled so the
-- signature accent is ember rather than magenta:
--   ember-bright #dd5500  (deep, burnt ember)
--   ember-hot    #ee6611  (brighter, hotter ember)
--
-- The grey ramp (base01–base05) is blended perceptually in HSLuv space between
-- the background (base00) and foreground (base06) anchors. See colorutils.lua.

local blend_hex = require("singularity.colorutils").blend_hex

if vim.g.colors_name then
  vim.cmd.hi("clear")
end

vim.g.colors_name = "singularity"
vim.o.termguicolors = true

local base00 = "#161616"
local base06 = "#ffffff"
local base09 = "#78a9ff"

-- Dark palette. base10/base12 are the ember accents (formerly the oxocarbon
-- pinks #ee5396 / #ff7eb6).
local dark = {
  base00 = base00,
  base01 = blend_hex(base00, base06, 0.085),
  base02 = blend_hex(base00, base06, 0.18),
  base03 = blend_hex(base00, base06, 0.3),
  base04 = blend_hex(base00, base06, 0.82),
  base05 = blend_hex(base00, base06, 0.95),
  base06 = base06,
  base07 = "#08bdba",
  base08 = "#3ddbd9",
  base09 = base09,
  base10 = "#dd5500", -- ember-bright (was #ee5396)
  base11 = "#33b1ff",
  base12 = "#ee6611", -- ember-hot   (was #ff7eb6)
  base13 = "#42be65",
  base14 = "#be95ff",
  base15 = "#82cfff",
  blend = "#131313",
  none = "NONE",
}

-- Light palette. A tonal counterpart of the dark theme rather than a separate
-- design: ember is the signature accent in the SAME roles (base10 errors and
-- headings, base12 functions), the syntax colours stay cool (blue/teal), and
-- every accent is WCAG-AA legible on white. The greys are a Material blue-grey
-- ramp so comments recede instead of rendering near-black. Because the bright
-- embers fail contrast on white, light uses deeper ember shades.
local light = {
  base00 = base06,    -- #ffffff
  base01 = "#eceff1", -- subtle bg (CursorLine, Pmenu)
  base02 = "#cfd8dc", -- selection
  base03 = "#78828a", -- comments / line numbers (dim, ~3.9:1)
  base04 = "#37474f", -- main foreground
  base05 = "#546e7a", -- secondary foreground
  base06 = "#263238", -- strong foreground
  base07 = "#0e7c7b", -- teal
  base08 = "#0a8385", -- cyan / functions
  base09 = "#1a66d6", -- blue / keywords
  base10 = "#b34400", -- ember-deep — signature (errors, headings); was #FF6F00
  base11 = "#0f52c4", -- royal blue
  base12 = "#c65300", -- ember — functions / decorators
  base13 = "#2a8049", -- green
  base14 = "#7b3fd4", -- violet / strings
  base15 = "#0e7693", -- cyan-blue / numbers
  blend = "#f4f6f8",  -- float background
  none = "NONE",
}

local singularity = (vim.o.background == "dark") and dark or light

vim.g["terminal_color_0"] = singularity.base01
vim.g["terminal_color_1"] = singularity.base11
vim.g["terminal_color_2"] = singularity.base14
vim.g["terminal_color_3"] = singularity.base13
vim.g["terminal_color_4"] = singularity.base09
vim.g["terminal_color_5"] = singularity.base15
vim.g["terminal_color_6"] = singularity.base08
vim.g["terminal_color_7"] = singularity.base05
vim.g["terminal_color_8"] = singularity.base03
vim.g["terminal_color_9"] = singularity.base11
vim.g["terminal_color_10"] = singularity.base14
vim.g["terminal_color_11"] = singularity.base13
vim.g["terminal_color_12"] = singularity.base09
vim.g["terminal_color_13"] = singularity.base15
vim.g["terminal_color_14"] = singularity.base07
vim.g["terminal_color_15"] = singularity.base06
vim.api.nvim_set_hl(0, "ColorColumn", {fg = singularity.none, bg = singularity.base01})
vim.api.nvim_set_hl(0, "Cursor", {fg = singularity.base00, bg = singularity.base04})
vim.api.nvim_set_hl(0, "CursorLine", {fg = singularity.none, bg = singularity.base01})
vim.api.nvim_set_hl(0, "CursorColumn", {fg = singularity.none, bg = singularity.base01})
vim.api.nvim_set_hl(0, "CursorLineNr", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "QuickFixLine", {fg = singularity.none, bg = singularity.base01})
vim.api.nvim_set_hl(0, "Error", {fg = singularity.base10, bg = singularity.base01})
vim.api.nvim_set_hl(0, "LineNr", {fg = singularity.base03, bg = singularity.base00})
vim.api.nvim_set_hl(0, "NonText", {fg = singularity.base02, bg = singularity.none})
vim.api.nvim_set_hl(0, "Normal", {fg = singularity.base04, bg = singularity.base00})
vim.api.nvim_set_hl(0, "Pmenu", {fg = singularity.base04, bg = singularity.base01})
vim.api.nvim_set_hl(0, "PmenuSbar", {fg = singularity.base04, bg = singularity.base01})
vim.api.nvim_set_hl(0, "PmenuSel", {fg = singularity.base08, bg = singularity.base02})
vim.api.nvim_set_hl(0, "PmenuThumb", {fg = singularity.base08, bg = singularity.base02})
vim.api.nvim_set_hl(0, "SpecialKey", {fg = singularity.base03, bg = singularity.none})
vim.api.nvim_set_hl(0, "Visual", {fg = singularity.none, bg = singularity.base02})
vim.api.nvim_set_hl(0, "VisualNOS", {fg = singularity.none, bg = singularity.base02})
vim.api.nvim_set_hl(0, "TooLong", {fg = singularity.none, bg = singularity.base02})
vim.api.nvim_set_hl(0, "Debug", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "Macro", {fg = singularity.base07, bg = singularity.none})
vim.api.nvim_set_hl(0, "MatchParen", {fg = singularity.none, bg = singularity.base02, underline = true})
vim.api.nvim_set_hl(0, "Bold", {fg = singularity.none, bg = singularity.none, bold = true})
vim.api.nvim_set_hl(0, "Italic", {fg = singularity.none, bg = singularity.none, italic = true})
vim.api.nvim_set_hl(0, "Underlined", {fg = singularity.none, bg = singularity.none, underline = true})
vim.api.nvim_set_hl(0, "DiagnosticWarn", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "DiagnosticError", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "DiagnosticInfo", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "DiagnosticHint", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {fg = singularity.base14, bg = singularity.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {fg = singularity.base10, bg = singularity.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {fg = singularity.base04, bg = singularity.none, undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {fg = singularity.base04, bg = singularity.none, undercurl = true})
vim.api.nvim_set_hl(0, "HealthError", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "HealthWarning", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "HealthSuccess", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "@comment", {link = "Comment"})
vim.api.nvim_set_hl(0, "@text.literal.commodity", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "@number", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "@number.date", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "@number.date.effective", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "@number.interval", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "@number.status", {fg = singularity.base12, bg = singularity.none})
vim.api.nvim_set_hl(0, "@number.quantity", {fg = singularity.base11, bg = singularity.none})
vim.api.nvim_set_hl(0, "@number.quantity.negative", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "LspCodeLens", {fg = singularity.none, bg = singularity.base03})
vim.api.nvim_set_hl(0, "LspReferenceText", {fg = singularity.none, bg = singularity.base03})
vim.api.nvim_set_hl(0, "LspReferenceread", {fg = singularity.none, bg = singularity.base03})
vim.api.nvim_set_hl(0, "LspReferenceWrite", {fg = singularity.none, bg = singularity.base03})
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "@lsp.type.class", {link = "Structure"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator", {link = "Decorator"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator.markdown", {link = "Structure"})
vim.api.nvim_set_hl(0, "@lsp.type.function", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.type.macro", {link = "Macro"})
vim.api.nvim_set_hl(0, "@lsp.type.method", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.type.struct", {link = "Structure"})
vim.api.nvim_set_hl(0, "@lsp.type.type", {link = "Type"})
vim.api.nvim_set_hl(0, "@lsp.type.typeParameter", {link = "Typedef"})
vim.api.nvim_set_hl(0, "@lsp.type.selfParameter", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinConstant", {link = "@constant.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.magicFunction", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.boolean", {link = "@boolean"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinType", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.comment", {link = "@comment"})
vim.api.nvim_set_hl(0, "@lsp.type.enum", {link = "@type"})
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence", {link = "@string.escape"})
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier", {link = "@punctuation.special"})
vim.api.nvim_set_hl(0, "@lsp.type.keyword", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.namespace", {link = "@namespace"})
vim.api.nvim_set_hl(0, "@lsp.type.number", {link = "@number"})
vim.api.nvim_set_hl(0, "@lsp.type.operator", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.type.parameter", {link = "@parameter"})
vim.api.nvim_set_hl(0, "@lsp.type.property", {link = "@property"})
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.string.rust", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", {link = "@type.definition"})
vim.api.nvim_set_hl(0, "@lsp.type.unresolvedReference", {link = "Error"})
vim.api.nvim_set_hl(0, "@lsp.type.variable", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.mod.readonly", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.mod.typeHint", {link = "Type"})
vim.api.nvim_set_hl(0, "@lsp.mod.builtin", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enum.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.defaultLibrary", {link = "@constant.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.async", {link = "@keyword.coroutine"})
vim.api.nvim_set_hl(0, "@lsp.typemod.macro.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.injected", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.typemod.string.injected", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.controlFlow", {link = "@exception"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.documentation", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.global", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.static", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {link = "Special"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.builtin", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.readonly", {link = "@method"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.injected", {link = "@variable"})
vim.api.nvim_set_hl(0, "Folded", {fg = singularity.base02, bg = singularity.base01})
vim.api.nvim_set_hl(0, "FoldColumn", {fg = singularity.base01, bg = singularity.base00})
vim.api.nvim_set_hl(0, "SignColumn", {fg = singularity.base01, bg = singularity.base00})
vim.api.nvim_set_hl(0, "Directory", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "EndOfBuffer", {fg = singularity.base01, bg = singularity.none})
vim.api.nvim_set_hl(0, "ErrorMsg", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "ModeMsg", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "MoreMsg", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "Question", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "Substitute", {fg = singularity.base01, bg = singularity.base08})
vim.api.nvim_set_hl(0, "WarningMsg", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "WildMenu", {fg = singularity.base08, bg = singularity.base01})
vim.api.nvim_set_hl(0, "helpHyperTextJump", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "helpSpecial", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "helpHeadline", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "helpHeader", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "DiffAdded", {fg = singularity.base07, bg = singularity.none})
vim.api.nvim_set_hl(0, "DiffChanged", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "DiffRemoved", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "DiffAdd", {bg = "#122f2f", fg = singularity.none})
vim.api.nvim_set_hl(0, "DiffChange", {bg = "#222a39", fg = singularity.none})
vim.api.nvim_set_hl(0, "DiffText", {bg = "#2f3f5c", fg = singularity.none})
vim.api.nvim_set_hl(0, "DiffDelete", {bg = "#361c28", fg = singularity.none})
vim.api.nvim_set_hl(0, "IncSearch", {fg = singularity.base06, bg = singularity.base10})
vim.api.nvim_set_hl(0, "Search", {fg = singularity.base01, bg = singularity.base08})
vim.api.nvim_set_hl(0, "TabLine", {link = "StatusLineNC"})
vim.api.nvim_set_hl(0, "TabLineFill", {link = "TabLine"})
vim.api.nvim_set_hl(0, "TabLineSel", {link = "StatusLine"})
vim.api.nvim_set_hl(0, "Title", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "VertSplit", {fg = singularity.base01, bg = singularity.base00})
vim.api.nvim_set_hl(0, "WinSeparator", {fg = singularity.base01, bg = singularity.base00})
vim.api.nvim_set_hl(0, "Boolean", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Character", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "Comment", {fg = singularity.base03, bg = singularity.none, italic = true})
vim.api.nvim_set_hl(0, "Conceal", {fg = singularity.none, bg = singularity.none})
vim.api.nvim_set_hl(0, "Conditional", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Constant", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "Decorator", {fg = singularity.base12, bg = singularity.none})
vim.api.nvim_set_hl(0, "Define", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Delimeter", {fg = singularity.base06, bg = singularity.none})
vim.api.nvim_set_hl(0, "Exception", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Float", {link = "Number"})
vim.api.nvim_set_hl(0, "Function", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "Identifier", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "Include", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Keyword", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Label", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Number", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "Operator", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "PreProc", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Repeat", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Special", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "SpecialChar", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "SpecialComment", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "Statement", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "StorageClass", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "String", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "Structure", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Tag", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "Todo", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "Type", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "Typedef", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "markdownBlockquote", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "markdownBold", {link = "Bold"})
vim.api.nvim_set_hl(0, "markdownItalic", {link = "Italic"})
vim.api.nvim_set_hl(0, "markdownBoldItalic", {fg = singularity.none, bg = singularity.none, bold = true, italic = true})
vim.api.nvim_set_hl(0, "markdownRule", {link = "Comment"})
vim.api.nvim_set_hl(0, "markdownH1", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "markdownH2", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH3", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH4", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH5", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownH6", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownHeadingDelimiter", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownHeadingRule", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "markdownUrl", {fg = singularity.base14, bg = singularity.none, underline = true})
vim.api.nvim_set_hl(0, "markdownCode", {link = "String"})
vim.api.nvim_set_hl(0, "markdownCodeBlock", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "markdownCodeDelimiter", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "markdownUrl", {link = "String"})
vim.api.nvim_set_hl(0, "markdownListMarker", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "markdownOrderedListMarker", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "@markup", {link = "@none"})
vim.api.nvim_set_hl(0, "@markup.environment", {link = "Macro"})
vim.api.nvim_set_hl(0, "@markup.environment.name", {link = "Type"})
vim.api.nvim_set_hl(0, "@markup.emphasis", {italic = true})
vim.api.nvim_set_hl(0, "@markup.italic", {italic = true})
vim.api.nvim_set_hl(0, "@markup.strikethrough", {strikethrough = true})
vim.api.nvim_set_hl(0, "@markup.strong", {bold = true})
vim.api.nvim_set_hl(0, "@markup.underline", {underline = true})
vim.api.nvim_set_hl(0, "@markup.heading", {link = "Title"})
vim.api.nvim_set_hl(0, "@markup.heading.marker", {link = "markdownHeadingDelimiter"})
vim.api.nvim_set_hl(0, "@markup.heading.1.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.2.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.3.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.4.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.5.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.6.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.7.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.heading.8.markdown", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "@markup.link", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.label", {underline = true})
vim.api.nvim_set_hl(0, "@markup.link.label.symbol", {link = "markdownItalic"})
vim.api.nvim_set_hl(0, "@markup.link.label.markdown_inline", {link = "markdownItalic"})
vim.api.nvim_set_hl(0, "@markup.link.title", {link = "Title"})
vim.api.nvim_set_hl(0, "@markup.link.url", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.destination", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@markup.link.description", {fg = singularity.blend, underline = true, italic = true})
vim.api.nvim_set_hl(0, "@markup.list", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.bullet", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.checked", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.markdown", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.ordered", {link = "markdownOrderedListMarker"})
vim.api.nvim_set_hl(0, "@markup.list.unchecked", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "@markup.math", {link = "Special"})
vim.api.nvim_set_hl(0, "@markup.raw", {link = "String"})
vim.api.nvim_set_hl(0, "@markup.raw.markdown_inline", {link = "String"})
vim.api.nvim_set_hl(0, "@markup.quote", {link = "markdownBlockquote"})
vim.api.nvim_set_hl(0, "@markup.literal", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "@markup.code.block", {link = "markdownCodeBlock"})
vim.api.nvim_set_hl(0, "@markup.rule", {link = "Comment"})
vim.api.nvim_set_hl(0, "asciidocAttributeEntry", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "asciidocAttributeList", {link = "asciidocAttributeEntry"})
vim.api.nvim_set_hl(0, "asciidocAttributeRef", {link = "asciidocAttributeEntry"})
vim.api.nvim_set_hl(0, "asciidocHLabel", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "asciidocOneLineTitle", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "asciidocQuotedMonospaced", {link = "markdownBlockquote"})
vim.api.nvim_set_hl(0, "asciidocURL", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "@comment", {link = "Comment"})
vim.api.nvim_set_hl(0, "@error", {fg = singularity.base11, bg = singularity.none})
vim.api.nvim_set_hl(0, "@operator", {link = "Operator"})
vim.api.nvim_set_hl(0, "@punctuation.delimiter", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "@punctuation.bracket", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "@punctuation.special", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "@string", {link = "String"})
vim.api.nvim_set_hl(0, "@string.regex", {fg = singularity.base07, bg = singularity.none})
vim.api.nvim_set_hl(0, "@string.escape", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "@character", {link = "Character"})
vim.api.nvim_set_hl(0, "@boolean", {link = "Boolean"})
vim.api.nvim_set_hl(0, "@number", {link = "Number"})
vim.api.nvim_set_hl(0, "@float", {link = "Float"})
vim.api.nvim_set_hl(0, "@function", {fg = singularity.base12, bg = singularity.none, bold = true})
vim.api.nvim_set_hl(0, "@function.builtin", {fg = singularity.base12, bg = singularity.none})
vim.api.nvim_set_hl(0, "@function.macro", {fg = singularity.base07, bg = singularity.none})
vim.api.nvim_set_hl(0, "@method", {fg = singularity.base07, bg = singularity.none})
vim.api.nvim_set_hl(0, "@constructor", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "@parameter", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "@keyword", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "@keyword.function", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "@keyword.operator", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "@conditional", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "@repeat", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "@label", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "@include", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "@exception", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "@type", {link = "Type"})
vim.api.nvim_set_hl(0, "@type.builtin", {link = "Type"})
vim.api.nvim_set_hl(0, "@attribute", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "@field", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "@property", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "@variable", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "@variable.builtin", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "@constant", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "@constant.builtin", {fg = singularity.base07, bg = singularity.none})
vim.api.nvim_set_hl(0, "@constant.macro", {fg = singularity.base07, bg = singularity.none})
vim.api.nvim_set_hl(0, "@namespace", {fg = singularity.base07, bg = singularity.none})
vim.api.nvim_set_hl(0, "@symbol", {fg = singularity.base15, bg = singularity.none, bold = true})
vim.api.nvim_set_hl(0, "@text", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "@text.strong", {fg = singularity.none, bg = singularity.none})
vim.api.nvim_set_hl(0, "@text.emphasis", {fg = singularity.base10, bg = singularity.none, bold = true})
vim.api.nvim_set_hl(0, "@text.underline", {fg = singularity.base10, bg = singularity.none, underline = true})
vim.api.nvim_set_hl(0, "@text.strike", {fg = singularity.base10, bg = singularity.none, strikethrough = true})
vim.api.nvim_set_hl(0, "@text.title", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "@text.literal", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "@text.uri", {fg = singularity.base14, bg = singularity.none, underline = true})
vim.api.nvim_set_hl(0, "@tag", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "@tag.attribute", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "@tag.delimiter", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "@tag.builtin.tsx", {link = "@tag.tsx"})
vim.api.nvim_set_hl(0, "@reference", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "NvimInternalError", {fg = singularity.base00, bg = singularity.base08})
vim.api.nvim_set_hl(0, "NormalFloat", {fg = singularity.base05, bg = singularity.blend})
vim.api.nvim_set_hl(0, "FloatBorder", {fg = singularity.blend, bg = singularity.blend})
vim.api.nvim_set_hl(0, "NormalNC", {fg = singularity.base04, bg = singularity.base00})
vim.api.nvim_set_hl(0, "TermCursor", {fg = singularity.base00, bg = singularity.base04})
vim.api.nvim_set_hl(0, "TermCursorNC", {fg = singularity.base00, bg = singularity.base04})
vim.api.nvim_set_hl(0, "StatusLine", {fg = singularity.base04, bg = singularity.base00})
vim.api.nvim_set_hl(0, "StatusLineNC", {fg = singularity.base04, bg = singularity.base01})
vim.api.nvim_set_hl(0, "StatusReplace", {fg = singularity.base00, bg = singularity.base08})
vim.api.nvim_set_hl(0, "StatusInsert", {fg = singularity.base00, bg = singularity.base12})
vim.api.nvim_set_hl(0, "StatusVisual", {fg = singularity.base00, bg = singularity.base14})
vim.api.nvim_set_hl(0, "StatusTerminal", {fg = singularity.base00, bg = singularity.base11})
vim.api.nvim_set_hl(0, "StatusNormal", {fg = singularity.base00, bg = singularity.base15})
vim.api.nvim_set_hl(0, "StatusCommand", {fg = singularity.base00, bg = singularity.base13})
vim.api.nvim_set_hl(0, "StatusLineDiagnosticWarn", {fg = singularity.base14, bg = singularity.base00, bold = true})
vim.api.nvim_set_hl(0, "StatusLineDiagnosticError", {fg = singularity.base10, bg = singularity.base00, bold = true})
vim.api.nvim_set_hl(0, "TelescopeBorder", {fg = singularity.blend, bg = singularity.blend})
vim.api.nvim_set_hl(0, "TelescopePromptBorder", {fg = singularity.base02, bg = singularity.base02})
vim.api.nvim_set_hl(0, "TelescopePromptNormal", {fg = singularity.base05, bg = singularity.base02})
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", {fg = singularity.base08, bg = singularity.base02})
vim.api.nvim_set_hl(0, "TelescopeNormal", {fg = singularity.none, bg = singularity.blend})
vim.api.nvim_set_hl(0, "TelescopePreviewTitle", {fg = singularity.base02, bg = singularity.base12})
vim.api.nvim_set_hl(0, "TelescopePromptTitle", {fg = singularity.base02, bg = singularity.base11})
vim.api.nvim_set_hl(0, "TelescopeResultsTitle", {fg = singularity.blend, bg = singularity.blend})
vim.api.nvim_set_hl(0, "TelescopeSelection", {fg = singularity.none, bg = singularity.base02})
vim.api.nvim_set_hl(0, "TelescopePreviewLine", {fg = singularity.none, bg = singularity.base01})
vim.api.nvim_set_hl(0, "TelescopeMatching", {fg = singularity.base08, bg = singularity.none, bold = true, italic = true})
vim.api.nvim_set_hl(0, "NotifyERRORBorder", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyWARNBorder", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyINFOBorder", {fg = singularity.base05, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGBorder", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyTRACEBorder", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyERRORIcon", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyWARNIcon", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyINFOIcon", {fg = singularity.base05, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGIcon", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyTRACEIcon", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyERRORTitle", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyWARNTitle", {fg = singularity.base14, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyINFOTitle", {fg = singularity.base05, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "NotifyTRACETitle", {fg = singularity.base13, bg = singularity.none})
vim.api.nvim_set_hl(0, "CmpItemAbbr", {fg = "#adadad", bg = singularity.none})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", {fg = singularity.base05, bg = singularity.none, bold = true})
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", {fg = singularity.base04, bg = singularity.none, bold = true})
vim.api.nvim_set_hl(0, "CmpItemMenu", {fg = singularity.base04, bg = singularity.none, italic = true})
vim.api.nvim_set_hl(0, "CmpItemKindInterface", {fg = singularity.base01, bg = singularity.base08})
vim.api.nvim_set_hl(0, "CmpItemKindColor", {fg = singularity.base01, bg = singularity.base08})
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", {fg = singularity.base01, bg = singularity.base08})
vim.api.nvim_set_hl(0, "CmpItemKindText", {fg = singularity.base01, bg = singularity.base09})
vim.api.nvim_set_hl(0, "CmpItemKindEnum", {fg = singularity.base01, bg = singularity.base09})
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", {fg = singularity.base01, bg = singularity.base09})
vim.api.nvim_set_hl(0, "CmpItemKindConstant", {fg = singularity.base01, bg = singularity.base10})
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", {fg = singularity.base01, bg = singularity.base10})
vim.api.nvim_set_hl(0, "CmpItemKindReference", {fg = singularity.base01, bg = singularity.base10})
vim.api.nvim_set_hl(0, "CmpItemKindFunction", {fg = singularity.base01, bg = singularity.base11})
vim.api.nvim_set_hl(0, "CmpItemKindStruct", {fg = singularity.base01, bg = singularity.base11})
vim.api.nvim_set_hl(0, "CmpItemKindClass", {fg = singularity.base01, bg = singularity.base11})
vim.api.nvim_set_hl(0, "CmpItemKindModule", {fg = singularity.base01, bg = singularity.base11})
vim.api.nvim_set_hl(0, "CmpItemKindOperator", {fg = singularity.base01, bg = singularity.base11})
vim.api.nvim_set_hl(0, "CmpItemKindField", {fg = singularity.base01, bg = singularity.base12})
vim.api.nvim_set_hl(0, "CmpItemKindProperty", {fg = singularity.base01, bg = singularity.base12})
vim.api.nvim_set_hl(0, "CmpItemKindEvent", {fg = singularity.base01, bg = singularity.base12})
vim.api.nvim_set_hl(0, "CmpItemKindUnit", {fg = singularity.base01, bg = singularity.base13})
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", {fg = singularity.base01, bg = singularity.base13})
vim.api.nvim_set_hl(0, "CmpItemKindFolder", {fg = singularity.base01, bg = singularity.base13})
vim.api.nvim_set_hl(0, "CmpItemKindVariable", {fg = singularity.base01, bg = singularity.base14})
vim.api.nvim_set_hl(0, "CmpItemKindFile", {fg = singularity.base01, bg = singularity.base14})
vim.api.nvim_set_hl(0, "CmpItemKindMethod", {fg = singularity.base01, bg = singularity.base15})
vim.api.nvim_set_hl(0, "CmpItemKindValue", {fg = singularity.base01, bg = singularity.base15})
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", {fg = singularity.base01, bg = singularity.base15})
vim.api.nvim_set_hl(0, "NvimTreeImageFile", {fg = singularity.base12, bg = singularity.none})
vim.api.nvim_set_hl(0, "NvimTreeFolderIcon", {fg = singularity.base12, bg = singularity.none})
vim.api.nvim_set_hl(0, "NvimTreeWinSeparator", {fg = singularity.base00, bg = singularity.base00})
vim.api.nvim_set_hl(0, "NvimTreeFolderName", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "NvimTreeIndentMarker", {fg = singularity.base02, bg = singularity.none})
vim.api.nvim_set_hl(0, "NvimTreeEmptyFolderName", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "NvimTreeOpenedFolderName", {fg = singularity.base15, bg = singularity.none})
vim.api.nvim_set_hl(0, "NvimTreeNormal", {fg = singularity.base04, bg = singularity.base00})
vim.api.nvim_set_hl(0, "NeogitBranch", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "NeogitRemote", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "NeogitHunkHeader", {fg = singularity.base04, bg = singularity.base02})
vim.api.nvim_set_hl(0, "NeogitHunkHeaderHighlight", {fg = singularity.base04, bg = singularity.base03})
vim.api.nvim_set_hl(0, "GitSignsCurrentLineBlame", {link = "Comment"})
vim.api.nvim_set_hl(0, "HydraRed", {fg = singularity.base12, bg = singularity.none})
vim.api.nvim_set_hl(0, "HydraBlue", {fg = singularity.base09, bg = singularity.none})
vim.api.nvim_set_hl(0, "HydraAmaranth", {fg = singularity.base10, bg = singularity.none})
vim.api.nvim_set_hl(0, "HydraTeal", {fg = singularity.base08, bg = singularity.none})
vim.api.nvim_set_hl(0, "HydraHint", {fg = singularity.none, bg = singularity.blend})
vim.api.nvim_set_hl(0, "alpha1", {fg = singularity.base03, bg = singularity.none})
vim.api.nvim_set_hl(0, "alpha2", {fg = singularity.base04, bg = singularity.none})
vim.api.nvim_set_hl(0, "alpha3", {fg = singularity.base03, bg = singularity.none})
vim.api.nvim_set_hl(0, "CodeBlock", {fg = singularity.none, bg = singularity.base01})
vim.api.nvim_set_hl(0, "BufferLineDiagnostic", {fg = singularity.base10, bg = singularity.none, bold = true})
vim.api.nvim_set_hl(0, "BufferLineDiagnosticVisible", {fg = singularity.base10, bg = singularity.none, bold = true})
vim.api.nvim_set_hl(0, "htmlH1", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "mkdRule", {link = "markdownRule"})
vim.api.nvim_set_hl(0, "mkdListItem", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "mkdListItemCheckbox", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "VimwikiHeader1", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader2", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader3", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader4", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader5", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeader6", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiHeaderChar", {link = "markdownH1"})
vim.api.nvim_set_hl(0, "VimwikiList", {link = "markdownListMarker"})
vim.api.nvim_set_hl(0, "VimwikiLink", {link = "markdownUrl"})
vim.api.nvim_set_hl(0, "VimwikiCode", {link = "markdownCode"})
vim.api.nvim_set_hl(0, "FlashLabel", {fg = singularity.base05, bg = singularity.base00, bold = true})

-- Light-mode fixups. A few groups in the shared body assume the foreground that
-- sits on an accent background is light (true in dark, where base06 = #ffffff).
-- Re-point them for the light palette so contrast holds. Dark is unaffected.
if vim.o.background == "light" then
  vim.api.nvim_set_hl(0, "IncSearch", { fg = singularity.base00, bg = singularity.base10 })
end

return { singularity = singularity }
